name: Teacher Discipline Scraper
on:
  workflow_dispatch:
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.12'
  
      - name: Run EPC Scraper
        run: python EPC.py
